"""Авторизация"""
btn_to_login = "//button[@class='AppHeader-module__loginLink___332sz']"
input_email = "//input[@class='Input-module__control___2YQAv']"
input_password = "//input[@class='PasswordInput-module__control___5NmhT']"
btn_sign = "//button[@class='generalStyles-module__submitButton___tRe22 Button-module__wrapper___3P2dN Button-module__wrapper_primary___3gzaR Button-module__wrapper_block___3MTUt']"
name_for_check = "//div[@class='profile-shortInfo-name']"
popup = "//div[@class='popmechanic-close']"
accept_cookies = "//button[@id='rcc-confirm-button']"
btn_header_cart = "//button[@class='CartHeaderIcon-module__button___wdgl0']"
remove_cart = "//button[@class='CloseButton-module__wrapper___3W02P CartProduct-module__deleteIcon___35joC CartProduct-module__deleteButton___21_GZ CartProductMain-module__deleteButton___ccrOQ']"
close_cart = "//button[@class='CloseButton-module__wrapper___3W02P SidePanel-module__closeButton___15vdA']"

"""Каталог"""
btn_open_catalog = "(//a[@class='AppNav-module__link___2cpvw'])[3]"
btn_to_shoes = "(//li[@class='Category-module__categoryBranch___12sP_'])[4]"
btn_upper_shoes = "(//a[@class='Category-module__categoryLink___3Os1t'])[10]"
filter_of_size = "(//i[@class='icon-caret-down'])[1]"
select_size = "(//label[@class='Checkbox-module__checkbox___1lIJo Filter-module__chip___2Xol3 Checkbox-module__size___36L1X'])[3]"
filter_of_style = "(//div[@class='Filter-module__filter___2WLsM'])[2]"
select_style = "(//label[@class='Checkbox-module__checkbox___1lIJo Filter-module__chip___2Xol3'])[3]"
filter_of_color = "(//div[@class='Filter-module__filter___2WLsM'])[3]"
select_color = "//span[@class='Checkbox-module__colorBox___L_rxe Checkbox-module__blackColorBox___3bikG']"
filter_of_price = "(//div[@class='Filter-module__filter___2WLsM'])[4]"
select_price = "//div[@class='rc-slider-handle rc-slider-handle-2']"

filter_of_sorted = "(//div[@class='Filter-module__filter___2WLsM'])[5]"
select_sort = "(//div[@class='Filter-module__filter___2WLsM'])[5]"

btn_accept = "//button[@class='CloseButton-module__wrapper___3W02P SidePanel-module__closeButton___15vdA FiltersResetAllButton-module__closeButton___3TQFM']"

open_shoes = "(//div[@class='catalog-item size-1x'])[1]"
shoes_size = "(//div[@class='ProductSizePicker-module__size___1EXea ProductSizePicker-module__size_danger___2IEML'])[4]"

shoes_title = "//h1[@class='ProductDescription-module__name___3Lajq']"
shoes_price = "//div[@class='Price-module__wrapper___1Fvoz']"
btn_to_buy = "(//button[@class='ProductSalesActions-module__cartButton___37NOR PurchaseButton-module__wrapper___1699U Button-module__wrapper___3P2dN Button-module__wrapper_primary___3gzaR Button-module__wrapper_large___3M_fl Button-module__wrapper_block___3MTUt'])[1]"

"""Попап после добавления в корзину"""
popup_btn_buy = "//a[@class='CartPopup-module__button___3MgJX Button-module__wrapper___3P2dN Button-module__wrapper_primary___3gzaR']"

"""Корзина"""
total_shoes_title = "//h5[@class='CartProduct-module__title___31dR-']"
total_shoes_price = "(//div[@class='PurchaseTotal-module__row___2E3qx PurchaseTotal-module__total___4D8NV'])[1]"
total_btn_buy = "//button[@data-tt='checkout_button']"
